name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build

      - name: Check build output
        run: |
          if [ ! -f dist/index.html ]; then
            echo "🚨 Build failed: dist/index.html not found!"
            exit 1
          fi
          echo "✨ Build output verified: dist/index.html exists."

      - name: Copy build to docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -r dist/* docs/
          cp dist/.nojekyll docs/.nojekyll

      # List docs/ contents for debugging
      - name: List docs/ contents
        run: |
          echo "Contents of docs/:"
          ls -l docs/

      # Commit and push docs/ using GITHUB_TOKEN
      - name: Commit and push docs/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --cached --quiet || git commit -m "Update docs folder for GitHub Pages [skip ci]"
          git push

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
