name: Selenium Link Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  selenium-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Install Chromium browser
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Run Selenium link tests
        env:
          LOCAL_DOCS_URL: 'file://${{ github.workspace }}/docs/index.html'
        run: |
          python test_selenium_links.py
